server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  h2:
    console:
      enabled: true

logging:
  level: 
    org.hibernate.sql: debug